import Head from "next/head";
import { Inter } from "next/font/google";
import LockScreen from "@/components/lock-screen";
import HomePage from "@/components/home-page";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/store/reducers/reducers";
import { updateLock } from "@/store/mySlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();
  const isLocked = useSelector((state: RootState) => state.myReducer.isLocked);
  return (
    <>
      <Head>
        <title>Vaibhav Baheti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLocked ? (
        <div onClick={() => dispatch(updateLock(false))}>
          <LockScreen />
        </div>
      ) : (
        <HomePage />
      )}
    </>
  );
}
